# ---------------------------------------------------------------
# Social media posts about Netflix
# ---------------------------------------------------------------
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  labels:
    eventstreams.ibm.com/cluster: kafka-connect-cluster
  name: bluesky-netflix-connector
  namespace: event-automation
spec:
  # connector config
  class: uk.co.dalelane.kafkaconnect.bluesky.source.BlueskySourceConnector
  config:
    # format
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    # target
    bluesky.topic: BLUESKY.NETFLIX
    # config
    bluesky.searchterm: netflix
    bluesky.poll.ms: 120000
    bluesky.identity: ${file:/mnt/connect-creds-bluesky:IDENTITY}
    bluesky.password: ${file:/mnt/connect-creds-bluesky:APP_PASSWORD}
  # scaling
  tasksMax: 1
  # error tolerance
  autoRestart:
    enabled: true

---
# ---------------------------------------------------------------
# Social media posts about Xbox
# ---------------------------------------------------------------
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  labels:
    eventstreams.ibm.com/cluster: kafka-connect-cluster
  name: bluesky-xbox-connector
  namespace: event-automation
spec:
  # connector config
  class: uk.co.dalelane.kafkaconnect.bluesky.source.BlueskySourceConnector
  config:
    # format
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    # target
    bluesky.topic: BLUESKY.XBOX
    # config
    bluesky.searchterm: xbox
    bluesky.poll.ms: 120000
    bluesky.identity: ${file:/mnt/connect-creds-bluesky:IDENTITY}
    bluesky.password: ${file:/mnt/connect-creds-bluesky:APP_PASSWORD}
  # scaling
  tasksMax: 1
  # error tolerance
  autoRestart:
    enabled: true
