# ---------------------------------------------------------------
# MQTT source
# ---------------------------------------------------------------
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
  name: mqtt-source-topic
  namespace: event-automation
spec:
  topicName: MQTT.SOURCE
  partitions: 1
  replicas: 1
  config:
    min.insync.replicas: '1'
    # 10 MB
    retention.bytes: '10000000'
    # 1 week
    retention.ms: '604800000'

---
# ---------------------------------------------------------------
# MQTT sink
# ---------------------------------------------------------------
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
  name: mqtt-sink-topic
  namespace: event-automation
spec:
  topicName: MQTT.SINK
  partitions: 1
  replicas: 1
  config:
    min.insync.replicas: '1'
    # 10 MB
    retention.bytes: '10000000'
    # 1 week
    retention.ms: '604800000'
