# ---------------------------------------------------------------
# PostgreSQL updates
# ---------------------------------------------------------------
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  labels:
    eventstreams.ibm.com/cluster: kafka-connect-cluster
  name: postgresql-connector
  namespace: event-automation
spec:
  # connector config
  class: io.debezium.connector.postgresql.PostgresConnector
  config:
    # format
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    # source
    topic.prefix: pgsqldemo
    # connection details
    database.hostname: ${file:/mnt/connect-creds-postgresql:host}
    database.dbname : ${file:/mnt/connect-creds-postgresql:dbname}
    database.port: ${file:/mnt/connect-creds-postgresql:port}
    database.user: ${file:/mnt/connect-creds-postgresql:user}
    database.password: ${file:/mnt/connect-creds-postgresql:password}
    # config
    slot.name: pgsqldemo
    plugin.name: pgoutput
    database.server.name: pgsqldemo
    # SSL/TLS config
    database.sslmode: prefer
    database.sslrootcert: /mnt/connect-cert-postgresql/ca.crt
    database.sslcert: /mnt/connect-cert-postgresql/tls.crt
  # scaling
  tasksMax: 1
  # error tolerance
  autoRestart:
    enabled: true
