# ---------------------------------------------------------------
# HTTP POST
# ---------------------------------------------------------------
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  labels:
    eventstreams.ibm.com/cluster: my-kafka-cluster
  name: restapi-sink-topic
  namespace: event-automation
spec:
  topicName: RESTAPI.SINK
  partitions: 1
  replicas: 1
  config:
    min.insync.replicas: '1'
    # 10 MB
    retention.bytes: '10000000'
    # 1 day
    retention.ms: '86400000'
